# SPDX-FileCopyrightText: 2020-2021 HH Partners
# 
# SPDX-License-Identifier: MIT

[workspace]

members = [
  "analyze",
  "cli",
  "fossology",
  "policy_engine",
  "spdx",
  "utilities",
  "notice",
]