# SPDX-FileCopyrightText: 2020 HH Partners
#
# SPDX-License-Identifier: MIT

name: Release

on:
  push:
    branches:
      - main

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: rust
          package-name: doubleopen_cli
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          pull-request-title-pattern: "chore: release ${version}"
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/cache@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          command: build
          args: --release
      - name: Upload release binary
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./target/release/doubleopen_cli
          asset_name: doubleopen_cli
          asset_content_type: application/x-binary
