name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: softprops/action-gh-release@v1
        with:
          files: target/release/doubleopen_cli
        env:
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}