# SPDX-FileCopyrightText: 2020 HH Partners
#
# SPDX-License-Identifier: MIT

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install libarchive
        run: sudo apt-get install libarchive-dev
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  reuse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1
